default_twitter: &default_twitter
  twitter_api_key: 'xB2eYxB48YkAqlI7zFjFo2Xb2'
  twitter_api_secret: 'g7suNE1XpXTA0awzre4WfMZVhxc5w4y78MzqK3yoTTlpGLEqlQ'

development:
  secret_key_base: 1b0b41df20e4cb724da83167ea61a0c3e33d35f3ad861d1300fa9151181540599fb35f1cf352d9c6177db992f071fd549b69e1780980edc87ef83f56426ed861
  <<: *default_twitter

test:
  secret_key_base: 8c0fdea62a16d7a46a11c8a4032ebe1b687768a795fbbcbc0fc97954171b0612dcc9dc50dbaca9b19487c0569b624756137d6a8f44aa59b52890f8cd7d2419f2
  <<: *default_twitter

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: '<%= ENV["TWITTER_CONSUMER_KEY"] %>'
  twitter_api_secret: '<%= ENV["TWITTER_CONSUMER_SECRET"] %>'
